version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mspr
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  mspr-back:
    image: mspr-back
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      MSPR_DB: "mariadb"
    ports:
      - "8080:8080"